# Generated by Django 5.1.5 on 2025-01-28 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter')], help_text='The platform for which this API key is valid (LinkedIn, Instagram, Twitter).', max_length=50)),
                ('api_key', models.CharField(help_text='The API key for accessing the social media platform.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the API key was created.')),
                ('user', models.ForeignKey(help_text='The user who owns this API key.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
